Update dependencies, set compileSdk to 35
EmmaTellblom/Mensinator pull request #164
Opened 2024-11-02 22:08 UTC by carstenhag

* Cleanup .toml
* Update AGP
* Use Compose compiler
* Update to Kotlin 2.0
* Set compileSdk to 35 (just changes the SDK we compile with, doesn't affect minSdk/targetSdk)

2024-11-02 22:14 UTC, carstenhag commented
Blocked by #165, AGP seems to have gotten more restrictive on wrong keys :)

2024-11-03 07:18 UTC, EmmaTellblom requested changes

2024-11-03 07:18 UTC, EmmaTellblom commented on gradle/wrapper/gradle-wrapper.properties
Wrong checksum for this gradle version :)

2024-11-03 09:27 UTC, EmmaTellblom approved these changes

2024-11-03 09:48 UTC, carstenhag commented on gradle/wrapper/gradle-wrapper.properties
Yep, woops

2024-11-03 13:16 UTC, merged